--!strict
--[[
	PhaseAlign — four dials, and turning one turns its neighbour as well.

	The logic one. Every dial reads 0 to 3 and the panel wants all four on the
	same target; pressing a dial advances it AND the dial to its right, wrapping
	round from the fourth to the first. Which means the obvious approach — fix
	dial one, fix dial two, fix dial three — breaks itself as it goes, and the
	player has to notice that the coupling is the puzzle rather than the
	obstacle.

	── IT IS DEALT BACKWARDS FROM SOLVED ───────────────────────────────────────
	This is the one decision in the file that matters. A board rolled at random
	is a board that may not be reachable, and an unreachable board is not a hard
	puzzle — it is a player pressing buttons in front of a machine that was never
	going to open, in the middle of a horde, with no way to tell that from being
	bad at it.

	So it is generated by STARTING at the answer and pressing a few times. Every
	press is its own inverse three times over (four presses of one dial return
	both dials it touches to where they were), and the presses all commute, so a
	board dealt in N presses is always finishable in at most 3N — twelve at the
	very worst, against the twenty-four a submission is allowed. There is no such
	thing as a dealt board that cannot be finished.

	── AND THE ANSWER IS THE PRESSES, NOT THE RESULT ───────────────────────────
	The submission is the sequence of dials the player pressed, and the server
	REPLAYS it from the board it dealt. Sending the final four values instead
	would be asking the client what it thinks the answer is and then checking its
	arithmetic against itself, which is not a check.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Shared = ReplicatedStorage:WaitForChild("Shared")
local GeneratorConfig = require(Shared.Config.GeneratorConfig)

local PhaseAlign = {}

PhaseAlign.Kind = GeneratorConfig.Kind.PhaseAlign

local DIALS = 4
--[[ Four positions per dial. Three is too few — a dial is never more than one
     press from anywhere and the coupling barely bites. Six starts to be
     bookkeeping rather than reasoning, and a player doing bookkeeping while
     being chased is a player who leaves. ]]
local MODULUS = 4
--[[ How far from solved a board is dealt. Two is often solvable by accident;
     seven is long enough that a player who loses their thread has to start the
     reasoning again rather than the puzzle. ]]
local MIN_SCRAMBLE = 3
local MAX_SCRAMBLE = 6
--[[ Re-rolls before the scramble is forced. A scramble whose presses happen to
     cancel deals a board that is already finished, which reads as a broken
     generator rather than as a lucky one. Rare, cheap to detect, and bounded
     because a while loop inside a round start is not something to leave open. ]]
local RESCRAMBLE_TRIES = 8

--[[ One press: this dial and the one to its right, both forward one, wrapping
     at both ends. Written once and used by the deal AND the check, so the rule
     the player learns and the rule the server enforces cannot drift apart. ]]
local function press(dials: { number }, index: number)
	local right = (index % DIALS) + 1
	dials[index] = (dials[index] + 1) % MODULUS
	dials[right] = (dials[right] + 1) % MODULUS
end

local function solved(dials: { number }, target: number): boolean
	for _, value in dials do
		if value ~= target then
			return false
		end
	end
	return true
end

export type Deal = { kind: string, challenge: { [string]: any }, solution: { target: number } }

function PhaseAlign.deal(random: Random): Deal
	local target = random:NextInteger(0, MODULUS - 1)

	local dials: { number } = {}
	local tries = 0
	repeat
		for index = 1, DIALS do
			dials[index] = target
		end
		for _ = 1, random:NextInteger(MIN_SCRAMBLE, MAX_SCRAMBLE) do
			press(dials, random:NextInteger(1, DIALS))
		end
		tries += 1
	until not solved(dials, target) or tries >= RESCRAMBLE_TRIES

	--[[ The forced answer for the one deal in a great many whose presses all
	     cancelled every time. One press from solved is a trivial board and a
	     trivial board is enormously better than a board that is already open. ]]
	if solved(dials, target) then
		press(dials, 1)
	end

	return {
		kind = PhaseAlign.Kind,
		--[[ The board and the target, which are both printed on the panel. What
		     is not sent is a route to the target — there are many, the player
		     finds one, and the server checks the one they walked. ]]
		challenge = { dials = dials, target = target, modulus = MODULUS },
		solution = { target = target },
	}
end

function PhaseAlign.check(deal: Deal, answer: { number }): boolean
	if #answer < 1 or #answer > GeneratorConfig.MaxAnswer then
		return false
	end

	--[[ Replayed on a COPY. The deal is kept for a re-open — a player who walks
	     away from a half-solved panel and comes back should find the same board —
	     so a check that turned the dials for real would rewrite the puzzle every
	     time somebody guessed at it. ]]
	local dials = table.clone(deal.challenge.dials)
	for _, index in answer do
		if typeof(index) ~= "number" or index % 1 ~= 0 or index < 1 or index > DIALS then
			return false
		end
		press(dials, index)
	end

	return solved(dials, deal.solution.target)
end

return PhaseAlign
